In [31]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.1.0'

In [4]:
file = 'python/ml-zoomcamp/housing.csv'

df = pd.read_csv(file)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [10]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [12]:
df['ocean_proximity'].nunique()

5

In [18]:
df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

259212.31179039303

In [16]:
df['ocean_proximity'] == 'NEAR BAY'

0         True
1         True
2         True
3         True
4         True
         ...  
20635    False
20636    False
20637    False
20638    False
20639    False
Name: ocean_proximity, Length: 20640, dtype: bool

In [19]:
fill_val = df['total_bedrooms'].mean()
print(fill_val)

537.8705525375618


In [20]:
new_df = df.fillna(value = fill_val)

In [21]:
new_df[new_df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

259212.31179039303

In [25]:
x = new_df[new_df['ocean_proximity'] == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']].values

In [26]:
x

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [29]:
xtx = x.T @ x
xtx

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [30]:
y = [950, 1300, 800, 1000, 1300]

In [35]:
w = (np.linalg.inv(xtx) @ x.T) @ y
w

array([23.12330961, -1.48124183,  5.69922946])